export const permissionsCopy = {
	eyebrow: "CONTROLO DE ACESSO",
	title: "Permissões",
	subtitle: "Veja exactamente o que uma pessoa pode fazer, o que fica mascarado e o que pode sair da organização.",
	evaluate: "Avaliar acesso",
	viewAs: "Ver como",
	exposure: "Exposição",
	resourceType: "Tipo de recurso",
	resourceId: "ID do recurso",
	workspaceId: "Workspace",
	projectId: "Projecto",
	ownerId: "Dono",
	teamId: "Equipa",
	classification: "Classificação",
	fields: "Campos a inspeccionar",
	action: "Acção específica",
	optional: "Opcional",
	targetUser: "Utilizador a simular",
	run: "Executar avaliação",
	simulate: "Simular pessoa",
	loadExposure: "Actualizar exposição",
	allowed: "Permitido",
	denied: "Negado",
	noResources: "Nenhuma exposição externa activa.",
	permissions: "Acções",
	external: "Externo",
	ai: "IA",
	export: "Exportação",
	watermark: "Watermark",
	fieldAccess: "Acesso aos campos",
	principal: "Principal",
	reason: "Motivo",
	matchedBy: "Regra encontrada",
	result: "Resultado",
	signInRequired: "É necessário iniciar sessão para consultar permissões.",
	executionError: "Não foi possível avaliar as permissões.",
	back: "Voltar ao workspace",
};
