export const tokens = {
  color: {
    acid500: "var(--color-acid-500)",
    ink950: "var(--color-ink-950)",
    ink900: "var(--color-ink-900)",
    ink850: "var(--color-ink-850)",
    ink800: "var(--color-ink-800)",
    ink750: "var(--color-ink-750)",
    ink700: "var(--color-ink-700)",
    ink600: "var(--color-ink-600)",
    ink500: "var(--color-ink-500)",
    ink400: "var(--color-ink-400)",
    ink300: "var(--color-ink-300)",
    ink200: "var(--color-ink-200)",
    ink100: "var(--color-ink-100)",
    ink050: "var(--color-ink-050)",
    ink000: "var(--color-ink-000)",
    warning: "var(--color-warning)",
    danger: "var(--color-danger)",
    info: "var(--color-info)",
  },
  bg: { canvas: "var(--bg-canvas)", chrome: "var(--bg-chrome)", surface: "var(--bg-surface)", raise: "var(--bg-surface-raise)", hover: "var(--bg-surface-hover)", inverted: "var(--bg-inverted)" },
  border: { subtle: "var(--border-subtle)", default: "var(--border-default)", strong: "var(--border-strong)", focus: "var(--border-focus)" },
  text: { primary: "var(--text-primary)", secondary: "var(--text-secondary)", tertiary: "var(--text-tertiary)", disabled: "var(--text-disabled)", onAcid: "var(--text-on-acid)", onInverted: "var(--text-on-inverted)" },
  radius: { xs: "var(--radius-xs)", sm: "var(--radius-sm)", md: "var(--radius-md)", lg: "var(--radius-lg)", xl: "var(--radius-xl)", full: "var(--radius-full)" },
  space: { 1: "var(--space-1)", 2: "var(--space-2)", 3: "var(--space-3)", 4: "var(--space-4)", 5: "var(--space-5)", 6: "var(--space-6)", 8: "var(--space-8)", 10: "var(--space-10)", 12: "var(--space-12)", 16: "var(--space-16)", 20: "var(--space-20)" },
  motion: { instant: "var(--dur-instant)", fast: "var(--dur-fast)", base: "var(--dur-base)", slow: "var(--dur-slow)" },
} as const;

export type OryonTokens = typeof tokens;
