export const graphCopy = {
	eyebrow: "WORK GRAPH",
	title: "Work Graph",
	subtitle: "Veja como o trabalho se liga, muda e chega ao cliente sem sair do mesmo grafo.",
	network: "Rede",
	customer360: "Customer 360",
	relations: "Relações",
	direction: "Direcção",
	depth: "Profundidade",
	allRelations: "Todas as relações",
	outgoing: "A partir do objecto",
	incoming: "Para o objecto",
	both: "Nos dois sentidos",
	object: "Objecto",
	chooseObject: "Escolha um objecto",
	connect: "Criar relação",
	from: "Origem",
	to: "Destino",
	relation: "Relação",
	position: "Posição",
	createRelation: "Ligar objectos",
	timeline: "Timeline",
	noTimeline: "Não existem eventos visíveis neste recorte.",
	noGraph: "Ainda não existem relações visíveis para este objecto.",
	loading: "A carregar o Work Graph…",
	refresh: "Actualizar",
	error: "Não foi possível carregar o Work Graph.",
	connected: "Relação criada.",
	cycle: "Esta relação criaria um ciclo protegido.",
	conflict: "Esta relação já existe.",
	permission: "Você não tem permissão para criar esta relação.",
	truncated: "A rede foi limitada pela profundidade seleccionada.",
	selected: "Objecto seleccionado",
	status: "Estado",
	priority: "Prioridade",
	owner: "Owner",
	workspace: "Workspace",
	nodeCount: "nodes",
	edgeCount: "edges",
	relationshipCount: "relações",
	journey: "Jornada",
	customerContext: "Contexto do cliente",
	convert: "Conversão",
	createConversion: "Marcar como conversão",
	link: "Ligar",
	newRelation: "Nova relação",
	close: "Fechar",
} as const;

export const graphRelations = [
	"BLOCKS",
	"BLOCKED_BY",
	"DUPLICATES",
	"RELATES_TO",
	"DERIVED_FROM",
	"CONVERTED_TO",
	"PARENT_OF",
	"MENTIONS",
	"ATTACHED_TO",
	"OWNS",
	"DISCUSSED_IN",
	"DECIDED_IN",
	"RESULTED_IN",
	"FINISH_TO_START",
	"START_TO_START",
	"FINISH_TO_FINISH",
	"START_TO_FINISH",
] as const;
