"use client";

import { useEffect, useState } from "react";
import { AgentSummarySchema, CheckpointDecisionSchema, WorkflowCreateInputSchema, WorkflowRunResponseSchema, WorkflowSummarySchema, type AgentSummary, type WorkflowRunResponse, type WorkflowSummary } from "@oryon/contracts/agents-automation";
import { Button, Card, EmptyState, ErrorState, InvertedPanel, Input, PageHeader, StatusChip, Textarea } from "@oryon/ui";
import "./automation.css";

function payloadData(value: unknown): unknown { if (!value || typeof value !== "object" || !("data" in value)) throw new Error("INVALID_RESPONSE"); return (value as { data: unknown }).data; }
function state(value: WorkflowRunResponse["state"]): "neutral" | "info" | "positive" | "danger" { if (value === "SUCCEEDED") return "positive"; if (["FAILED", "CANCELLED", "ROLLED_BACK"].includes(value)) return "danger"; if (value === "WAITING") return "info"; return "neutral"; }

export function AutomationsStudio(): React.ReactElement {
	const [workflows, setWorkflows] = useState<WorkflowSummary[]>([]); const [agents, setAgents] = useState<AgentSummary[]>([]); const [runs, setRuns] = useState<Record<string, WorkflowRunResponse>>({}); const [name, setName] = useState(""); const [key, setKey] = useState(""); const [description, setDescription] = useState(""); const [agentId, setAgentId] = useState(""); const [loading, setLoading] = useState(true); const [error, setError] = useState(false); const [creating, setCreating] = useState(false);
	async function load(): Promise<void> { setLoading(true); setError(false); try { const [workflowResponse, agentResponse] = await Promise.all([fetch("/api/workflows", { cache: "no-store" }), fetch("/api/agents", { cache: "no-store" })]); if (!workflowResponse.ok || !agentResponse.ok) throw new Error("LOAD_FAILED"); setWorkflows(WorkflowSummarySchema.array().parse(payloadData(await workflowResponse.json()))); const nextAgents = AgentSummarySchema.array().parse(payloadData(await agentResponse.json())); setAgents(nextAgents); if (!agentId && nextAgents[0]) setAgentId(nextAgents[0].id); } catch { setError(true); } finally { setLoading(false); } }
	useEffect(() => { void load(); }, []);
	async function create(): Promise<void> { if (!name.trim() || !key.trim() || !agentId || creating) return; setCreating(true); try { const input = WorkflowCreateInputSchema.parse({ key, name, description: description || undefined, trigger: { kind: "MANUAL" }, steps: [{ id: "run", name: "Executar agente", type: "AGENT", agentId, checkpoint: false }] }); const response = await fetch("/api/workflows", { method: "POST", headers: { "Content-Type": "application/json", "Idempotency-Key": crypto.randomUUID() }, body: JSON.stringify(input) }); if (!response.ok) throw new Error("CREATE_FAILED"); setName(""); setKey(""); setDescription(""); await load(); } finally { setCreating(false); } }
	async function activate(id: string): Promise<void> { const response = await fetch(`/api/workflows/${id}/state`, { method: "POST", headers: { "Content-Type": "application/json", "Idempotency-Key": crypto.randomUUID() }, body: JSON.stringify({ state: "ACTIVE" }) }); if (response.ok) await load(); }
	async function run(id: string): Promise<void> { const response = await fetch(`/api/workflows/${id}/runs`, { method: "POST", headers: { "Content-Type": "application/json", "Idempotency-Key": crypto.randomUUID() }, body: JSON.stringify({ input: {} }) }); if (!response.ok) return; const initial = WorkflowRunResponseSchema.parse(payloadData(await response.json())); setRuns((current) => ({ ...current, [id]: initial })); for (let attempt = 0; attempt < 25; attempt += 1) { const poll = await fetch(`/api/workflow-runs/${initial.id}`, { cache: "no-store" }); if (!poll.ok) break; const next = WorkflowRunResponseSchema.parse(payloadData(await poll.json())); setRuns((current) => ({ ...current, [id]: next })); if (!["RUNNING", "WAITING"].includes(next.state)) break; await new Promise((resolve) => setTimeout(resolve, 1200)); } }
	async function approval(run: WorkflowRunResponse, decision: "APPROVE" | "REJECT"): Promise<void> { const input = CheckpointDecisionSchema.parse({ decision }); const response = await fetch(`/api/workflow-runs/${run.id}/approve`, { method: "POST", headers: { "Content-Type": "application/json", "Idempotency-Key": crypto.randomUUID() }, body: JSON.stringify(input) }); if (!response.ok) return; const next = WorkflowRunResponseSchema.parse(payloadData(await response.json())); setRuns((current) => ({ ...current, [run.workflowId]: next })); }
	return <section className="automations-shell">
		<PageHeader title="Automations" description="Workflows orientados por eventos, horários, condições, acções e aprovação humana." />
		<div className="automation-layout"><Card><div className="automation-card-content"><strong>Novo workflow</strong><Input value={name} onChange={(event) => setName(event.target.value)} placeholder="Nome" /><Input value={key} onChange={(event) => setKey(event.target.value)} placeholder="workflow-key" /><Textarea value={description} onChange={(event) => setDescription(event.target.value)} placeholder="Descrição" /><label style={{ display: "grid", gap: "var(--space-2)", fontSize: "var(--text-caption)", color: "var(--text-secondary)" }}>Agente<select value={agentId} onChange={(event) => setAgentId(event.target.value)} disabled={agents.length === 0} style={{ minHeight: 44, padding: "0 var(--space-3)", borderRadius: "var(--radius-sm)", border: "1px solid var(--border-subtle)", background: "var(--bg-surface)", color: "var(--text-primary)" }}><option value="">Seleccionar</option>{agents.map((agent) => <option value={agent.id} key={agent.id}>{agent.name}</option>)}</select></label><Button variant="primary" onClick={() => { void create(); }} loading={creating} disabled={!agentId}>Criar workflow</Button></div></Card><InvertedPanel><div className="automation-card-content"><span className="automation-meta">Service design</span><strong>Trigger → condition → action → control</strong><span style={{ color: "var(--text-secondary)", fontSize: "var(--text-body-sm)" }}>O runtime guarda cada passo e pode parar antes de uma operação sensível.</span></div></InvertedPanel></div>
		{error ? <ErrorState title="Não foi possível carregar automations" detail="Verifique a ligação à API e tente novamente." /> : null}
		{!loading && workflows.length === 0 ? <EmptyState title="Nenhum workflow" detail="Crie um workflow para automatizar trabalho." /> : null}
		<div className="automation-list">{workflows.map((workflow) => { const runState = runs[workflow.id]; return <Card key={workflow.id} interactive><div className="automation-card-content"><div className="automation-row"><div><strong>{workflow.name}</strong><div className="automation-meta">{workflow.key} · {workflow.trigger.kind}</div></div><StatusChip state={workflow.state === "ACTIVE" ? "positive" : "neutral"}>{workflow.state}</StatusChip></div><div className="automation-actions">{workflow.state !== "ACTIVE" ? <Button variant="secondary" onClick={() => { void activate(workflow.id); }}>Activar</Button> : <Button variant="primary" onClick={() => { void run(workflow.id); }}>Executar agora</Button>}{runState ? <StatusChip state={state(runState.state)}>{runState.state}</StatusChip> : null}{runState?.waitingOnApprovalId ? <><StatusChip state="info">Aguarda aprovação</StatusChip><Button variant="primary" onClick={() => { void approval(runState, "APPROVE"); }}>Aprovar</Button><Button variant="secondary" onClick={() => { void approval(runState, "REJECT"); }}>Rejeitar</Button></> : null}</div>{runState ? <div className="automation-meta">{Array.isArray(runState.stepLog) ? runState.stepLog.length : 0} passos registados</div> : null}</div></Card>; })}</div>
	</section>;
}
