"use client";

import type { ReactNode, ChangeEvent } from "react";
import { Bell, Command, Grid2X2, Search, Settings, UserRound, X } from "lucide-react";
import { AnimatePresence, motion } from "motion/react";
import { useEffect, useMemo, useState } from "react";
import { IconButton, SearchField } from "./primitives.js";

export type NavItem = { href: string; label: string; count?: number };
export type CommandItem = { id: string; label: string; group: string; href?: string; keywords?: string[]; shortcut?: string };
export function SegmentedNav({ items, activeHref }: { items: NavItem[]; activeHref?: string }) { return <nav className="oryon-segmented-nav" aria-label="Navegação principal">{items.map((item) => <a key={item.href} href={item.href} className={activeHref === item.href ? "active" : undefined}>{item.label}{typeof item.count === "number" ? <span className="oryon-count-badge">{item.count}</span> : null}</a>)}</nav>; }
export function AppLauncher({ items }: { items: NavItem[] }) { const [open, setOpen] = useState(false); return <div className="oryon-popover-wrap"><IconButton label="Abrir aplicações" size="md" variant="surface" aria-expanded={open} onClick={() => setOpen((value) => !value)}><Grid2X2 size={18} strokeWidth={1.5} /></IconButton><AnimatePresence>{open ? <motion.div className="oryon-app-launcher" initial={{ opacity: 0, scale: 0.96 }} animate={{ opacity: 1, scale: 1 }} exit={{ opacity: 0, scale: 0.96 }} transition={{ duration: 0.14 }} role="menu">{items.slice(0, 9).map((item) => <a key={item.href} href={item.href} role="menuitem"><span className="oryon-launcher-icon"><Grid2X2 size={16} strokeWidth={1.5} /></span><span>{item.label}</span></a>)}</motion.div> : null}</AnimatePresence></div>; }
export function IconButtonRail({ children }: { children: ReactNode }) { return <div className="oryon-icon-button-rail">{children}</div>; }
export function CommandPalette({ items, placeholder = "Pesquisar no OryonOS", open, onOpenChange }: { items: CommandItem[]; placeholder?: string; open: boolean; onOpenChange: (open: boolean) => void }) { const [query, setQuery] = useState(""); useEffect(() => { const handler = (event: KeyboardEvent) => { if ((event.metaKey || event.ctrlKey) && event.key.toLowerCase() === "k") { event.preventDefault(); onOpenChange(!open); } if (event.key === "Escape") onOpenChange(false); }; window.addEventListener("keydown", handler); return () => window.removeEventListener("keydown", handler); }, [onOpenChange, open]); const filtered = useMemo(() => { const normalized = query.trim().toLocaleLowerCase("pt-PT"); if (!normalized) return items; return items.filter((item) => [item.label, item.group, ...(item.keywords ?? [])].join(" ").toLocaleLowerCase("pt-PT").includes(normalized)); }, [items, query]); const groups = useMemo(() => Array.from(new Set(filtered.map((item) => item.group))), [filtered]); if (!open) return null; return <div className="oryon-command-backdrop" role="presentation" onMouseDown={() => onOpenChange(false)}><motion.div className="oryon-command-palette" initial={{ opacity: 0, y: -8, scale: 0.98 }} animate={{ opacity: 1, y: 0, scale: 1 }} transition={{ duration: 0.22 }} role="dialog" aria-modal="true" aria-label="Command palette" onMouseDown={(event: React.MouseEvent<HTMLDivElement>) => event.stopPropagation()}><div className="oryon-command-search"><SearchField autoFocus value={query} onChange={(event: ChangeEvent<HTMLInputElement>) => setQuery(event.target.value)} placeholder={placeholder} /><IconButton label="Fechar" variant="ghost" onClick={() => onOpenChange(false)}><X size={18} strokeWidth={1.5} /></IconButton></div><div className="oryon-command-results">{groups.length === 0 ? <div className="oryon-command-empty">Nenhum resultado encontrado.</div> : groups.map((group) => <section key={group}><p>{group}</p>{filtered.filter((item) => item.group === group).slice(0, 8).map((item) => item.href ? <a key={item.id} href={item.href} onClick={() => onOpenChange(false)}><span>{item.label}</span>{item.shortcut ? <kbd>{item.shortcut}</kbd> : null}</a> : <button key={item.id} type="button" onClick={() => onOpenChange(false)}><span>{item.label}</span>{item.shortcut ? <kbd>{item.shortcut}</kbd> : null}</button>)}</section>)}</div><div className="oryon-command-footer"><span><Command size={14} strokeWidth={1.5} aria-hidden="true" /> Atalho</span><kbd>⌘K</kbd><span>Esc fecha</span></div></motion.div></div>; }
export function FloatingTopBar({ brand, navItems, activeHref, launcherItems, userName, userInitials, onCommandOpen, onSettings = () => undefined, onNotifications = () => undefined }: { brand: string; navItems: NavItem[]; activeHref?: string; launcherItems: NavItem[]; userName: string; userInitials: string; onCommandOpen: () => void; onSettings?: () => void; onNotifications?: () => void }) { return <header className="oryon-floating-topbar"><div className="oryon-topbar-zone"><a className="oryon-brand" href="/os" aria-label={brand}>{brand}</a><AppLauncher items={launcherItems} /></div><SegmentedNav items={navItems} {...(activeHref ? { activeHref } : {})} /><div className="oryon-topbar-zone oryon-topbar-actions"><IconButtonRail><IconButton label="Pesquisar" onClick={onCommandOpen}><Search size={18} strokeWidth={1.5} /></IconButton><IconButton label="Notificações" onClick={onNotifications}><Bell size={18} strokeWidth={1.5} /></IconButton><IconButton label="Definições" onClick={onSettings}><Settings size={18} strokeWidth={1.5} /></IconButton></IconButtonRail><span className="oryon-user-chip"><span className="oryon-avatar oryon-avatar-md">{userInitials}</span><span className="oryon-user-name">{userName}</span><UserRound size={16} strokeWidth={1.5} aria-hidden="true" /></span></div></header>; }
export function PageHeader({ title, description, backHref, actions }: { title: string; description?: string; backHref?: string; actions?: ReactNode }) { return <header className="oryon-page-header">{backHref ? <a className="oryon-page-back" href={backHref} aria-label="Voltar">‹</a> : null}<div><h1>{title}</h1>{description ? <p>{description}</p> : null}</div>{actions ? <div className="oryon-page-actions">{actions}</div> : null}</header>; }
export function AppShell({ brand = "OryonOS", navItems, launcherItems, activeHref, userName, userInitials, children }: { brand?: string; navItems: NavItem[]; launcherItems?: NavItem[]; activeHref?: string; userName: string; userInitials: string; children: ReactNode }) { const [commandOpen, setCommandOpen] = useState(false); const items: CommandItem[] = [...navItems.map((item) => ({ id: item.href, label: item.label, group: "Navegação", href: item.href })), { id: "command-work", label: "Abrir Work", group: "Acções", href: "/os/work", keywords: ["trabalho", "objectos"] }, { id: "command-graph", label: "Abrir Work Graph", group: "Acções", href: "/os/graph", keywords: ["grafo", "relações", "customer 360"] }]; return <div className="oryon-app-shell"><FloatingTopBar brand={brand} navItems={navItems} {...(activeHref ? { activeHref } : {})} launcherItems={launcherItems ?? navItems} userName={userName} userInitials={userInitials} onCommandOpen={() => setCommandOpen(true)} /><main className="oryon-app-content">{children}</main><CommandPalette items={items} open={commandOpen} onOpenChange={setCommandOpen} /></div>; }
