import type { ButtonHTMLAttributes, ChangeEventHandler, InputHTMLAttributes, MouseEventHandler, SelectHTMLAttributes, TextareaHTMLAttributes, ReactNode } from "react";
import { AlertCircle, Bot, Check, ChevronDown, Loader2, Search, X } from "lucide-react";
const cn = (...values: Array<string | false | null | undefined>) => values.filter(Boolean).join(" ");
export function Button({ variant = "primary", size = "md", loading, children, className, disabled, ...props }: ButtonHTMLAttributes<HTMLButtonElement> & { variant?: "primary" | "inverted" | "secondary" | "ghost" | "outline" | "danger"; size?: "sm" | "md" | "lg"; loading?: boolean }) { return <button {...props} disabled={disabled || loading} className={cn("oryon-button", `oryon-button-${variant}`, `oryon-button-${size}`, className)}>{loading ? <Loader2 className="oryon-spin" aria-hidden="true" size={16} strokeWidth={1.5} /> : null}<span>{children}</span></button>; }
export function IconButton({ label, variant = "ghost", size = "md", children, className, ...props }: ButtonHTMLAttributes<HTMLButtonElement> & { label: string; variant?: "ghost" | "surface" | "acid" | "inverted" | "danger"; size?: "sm" | "md" | "lg" }) { return <button {...props} type={props.type ?? "button"} aria-label={label} className={cn("oryon-icon-button", `oryon-icon-button-${variant}`, `oryon-icon-button-${size}`, className)}>{children}</button>; }
export function Input({ label, hint, error, ...props }: InputHTMLAttributes<HTMLInputElement> & { label?: string; hint?: string; error?: string }) { const hintId = "oryon-input-hint"; const errorId = "oryon-input-error"; const describedBy = [hint && hintId, error && errorId].filter(Boolean).join(" ") || undefined; return <label className="oryon-field">{label ? <span className="oryon-field-label">{label}</span> : null}<input {...props} aria-invalid={Boolean(error)} aria-describedby={describedBy} className={cn("oryon-input", props.className)} />{hint ? <span id={hintId} className="oryon-field-hint">{hint}</span> : null}{error ? <span id={errorId} className="oryon-field-error">{error}</span> : null}</label>; }
export function Textarea({ label, ...props }: TextareaHTMLAttributes<HTMLTextAreaElement> & { label?: string }) { return <label className="oryon-field">{label ? <span className="oryon-field-label">{label}</span> : null}<textarea {...props} className={cn("oryon-input oryon-textarea", props.className)} /></label>; }
export function NumberField(props: InputHTMLAttributes<HTMLInputElement> & { label?: string }) { return <Input {...props} inputMode="decimal" className={cn("oryon-number", props.className)} />; }
export function SelectPill({ label, placeholder, options, children, ...props }: SelectHTMLAttributes<HTMLSelectElement> & { label?: string; placeholder?: string; options?: Array<{ value: string; label: string }> }) { return <label className="oryon-select-wrap">{label ? <span className="oryon-field-label">{label}</span> : null}<span className="oryon-select-shell"><select {...props} className={cn("oryon-select-pill", props.className)}>{placeholder ? <option value="">{placeholder}</option> : null}{options?.map((option) => <option key={option.value} value={option.value}>{option.label}</option>)}{children}</select><ChevronDown aria-hidden="true" size={14} strokeWidth={1.5} /></span></label>; }
export function SearchField({ value, onChange, placeholder = "Pesquisar", ...props }: InputHTMLAttributes<HTMLInputElement> & { value?: string; onChange?: ChangeEventHandler<HTMLInputElement> }) { return <label className="oryon-search-field"><Search aria-hidden="true" size={16} strokeWidth={1.5} /><input {...props} value={value} onChange={onChange} placeholder={placeholder} /></label>; }
export function Toggle({ checked, onChange, label, disabled }: { checked: boolean; onChange: (checked: boolean) => void; label: string; disabled?: boolean }) { return <label className="oryon-toggle"><input type="checkbox" checked={checked} disabled={disabled} onChange={(event) => onChange(event.target.checked)} /><span className="oryon-toggle-track" aria-hidden="true"><span className="oryon-toggle-thumb" /></span><span>{label}</span></label>; }
export function Checkbox({ checked, onChange, label, disabled }: { checked: boolean; onChange: (checked: boolean) => void; label: string; disabled?: boolean }) { return <label className="oryon-check"><input type="checkbox" checked={checked} disabled={disabled} onChange={(event) => onChange(event.target.checked)} /><span className="oryon-check-box" aria-hidden="true">{checked ? <Check size={14} strokeWidth={2} /> : null}</span><span>{label}</span></label>; }
export function RadioGroup({ value, options, onChange, label }: { value: string; options: Array<{ value: string; label: string }>; onChange: (value: string) => void; label?: string }) { return <fieldset className="oryon-radio-group">{label ? <legend>{label}</legend> : null}{options.map((option) => <label key={option.value}><input type="radio" name={label ?? "oryon-radio"} checked={value === option.value} onChange={() => onChange(option.value)} /><span>{option.label}</span></label>)}</fieldset>; }
export function SegmentedTabs({ value, onChange, items }: { value: string; onChange: (value: string) => void; items: Array<{ value: string; label: string; count?: number }> }) { return <div className="oryon-segmented-tabs" role="tablist">{items.map((item) => <button key={item.value} type="button" role="tab" aria-selected={value === item.value} onClick={() => onChange(item.value)}>{item.label}{typeof item.count === "number" ? <span className="oryon-count-badge">{item.count}</span> : null}</button>)}</div>; }
export function Card({ children, interactive, selected, className, onMouseDown }: { children: ReactNode; interactive?: boolean; selected?: boolean; className?: string; onMouseDown?: MouseEventHandler<HTMLElement> }) { return <article onMouseDown={onMouseDown} className={cn("oryon-card", interactive && "oryon-card-interactive", selected && "oryon-card-selected", className)}>{children}</article>; }
export function InvertedPanel({ children, className }: { children: ReactNode; className?: string }) { return <section className={cn("oryon-inverted oryon-inverted-panel", className)}>{children}</section>; }
export function StatusChip({ state, tone, label, children }: { state?: "positive" | "warning" | "danger" | "neutral" | "info"; tone?: "positive" | "warning" | "danger" | "negative" | "neutral" | "info"; label?: string; children?: ReactNode }) { const resolvedState = state ?? (tone === "negative" ? "danger" : tone) ?? "neutral"; const content = children ?? label ?? null; return <span className={cn("oryon-status-chip", `oryon-status-${resolvedState}`)}>{content}</span>; }
export function CountBadge({ children }: { children: ReactNode }) { return <span className="oryon-count-badge">{children}</span>; }
export function LineItemTile({ value, label }: { value: string; label: string }) { return <div className="oryon-line-item"><strong>{value}</strong><span>{label}</span></div>; }
export function MetricCard({ label, value, footer, emphasis, compact }: { label: string; value: string | number; footer?: ReactNode; emphasis?: boolean; compact?: boolean }) { return <article className={cn("oryon-metric-card", emphasis && "oryon-metric-emphasis", compact && "oryon-metric-compact")}><span>{label}</span><strong>{value}</strong>{footer ? <div>{footer}</div> : null}</article>; }
export function ProgressTrack({ value, segments }: { value: number; segments?: Array<{ label: string; value: number }> }) { return <div className="oryon-progress"><div className="oryon-progress-track"><span style={{ width: `${Math.max(0, Math.min(value, 100))}%` }} /></div>{segments ? <div className="oryon-progress-segments">{segments.map((segment) => <span key={segment.label}><b>{segment.value}</b>{segment.label}</span>)}</div> : null}</div>; }
export function Avatar({ name, initials, size = "md", agent }: { name?: string; initials?: string; size?: "sm" | "md" | "lg"; agent?: boolean }) { const letters = initials ?? (name?.trim().split(/\s+/).map((part) => part[0] ?? "").join("").slice(0, 2).toUpperCase() || "?"); return <span className={cn("oryon-avatar", `oryon-avatar-${size}`, agent && "oryon-avatar-agent")} aria-label={name ?? letters}>{agent ? <Bot size={14} strokeWidth={1.5} /> : letters}</span>; }
export function AvatarStack({ names }: { names: string[] }) { return <div className="oryon-avatar-stack">{names.slice(0, 4).map((name) => <Avatar key={name} name={name} size="md" />)}{names.length > 4 ? <span className="oryon-avatar-overflow">+{names.length - 4}</span> : null}</div>; }
export function DataRow({ primary, secondary, status, amount, selected, avatarName, onClick }: { primary: string; secondary?: string; status?: ReactNode; amount?: string; selected?: boolean; avatarName?: string; onClick?: () => void }) { const content = <>{avatarName ? <Avatar name={avatarName} size="md" /> : null}<span className="oryon-data-row-copy"><strong>{primary}</strong>{secondary ? <small>{secondary}</small> : null}</span>{status ? <span>{status}</span> : null}{amount ? <code>{amount}</code> : null}</>; return onClick ? <button type="button" className={cn("oryon-data-row", selected && "oryon-data-row-selected")} onClick={onClick}>{content}</button> : <div className={cn("oryon-data-row", selected && "oryon-data-row-selected")}>{content}</div>; }
export function AddTile({ label = "Adicionar" }: { label?: string }) { return <button type="button" className="oryon-add-tile"><span aria-hidden="true">+</span>{label}</button>; }
export function EntityCard({ name, subtitle, onClick }: { name: string; subtitle?: string; onClick?: () => void }) { const content = <><Avatar name={name} size="md" /><span><strong>{name}</strong>{subtitle ? <small>{subtitle}</small> : null}</span></>; return onClick ? <button type="button" className="oryon-entity-card" onClick={onClick}>{content}</button> : <div className="oryon-entity-card">{content}</div>; }
export function ErrorState({ title, detail, action }: { title: string; detail: string; action?: ReactNode }) { return <div className="oryon-feedback oryon-feedback-error"><AlertCircle size={20} strokeWidth={1.5} aria-hidden="true" /><div><h3>{title}</h3><p>{detail}</p>{action ? <div>{action}</div> : null}</div></div>; }
export function EmptyState({ title, detail, action }: { title: string; detail: string; action?: ReactNode }) { return <div className="oryon-feedback"><div><h3>{title}</h3><p>{detail}</p>{action ? <div>{action}</div> : null}</div></div>; }
export function Skeleton({ className }: { className?: string }) { return <span className={cn("oryon-skeleton", className)} aria-hidden="true" />; }
export function Tooltip({ label, children }: { label: string; children: ReactNode }) { return <span className="oryon-tooltip-wrap"><span>{children}</span><span role="tooltip" className="oryon-tooltip">{label}</span></span>; }
export function Toast({ message, action, onDismiss }: { message: string; action?: ReactNode; onDismiss?: () => void }) { return <div className="oryon-toast" role="status" aria-live="polite"><span>{message}</span>{action ? <span>{action}</span> : null}{onDismiss ? <IconButton label="Fechar" onClick={onDismiss}><X size={16} strokeWidth={1.5} /></IconButton> : null}</div>; }
