ALTER TYPE "PageKind" ADD VALUE IF NOT EXISTS 'CANVAS';
ALTER TYPE "PageKind" ADD VALUE IF NOT EXISTS 'DATABASE_VIEW';
ALTER TYPE "PageKind" ADD VALUE IF NOT EXISTS 'BRIEF';
ALTER TYPE "PageKind" ADD VALUE IF NOT EXISTS 'NOTE';
