import type { FastifyInstance, FastifyRequest } from "fastify";
import { can } from "@oryon/core";
import { CommunicationRepository, PermissionRepository } from "@oryon/db/repositories";
import { getPrisma } from "@oryon/db";
import { ChannelCreateInputSchema, ChannelSchema, CommunicationEventSchema, DirectChannelCreateInputSchema, CatchUpQuerySchema, MessageConversionInputSchema, MessageConversionResponseSchema, MessageCreateInputSchema, MessageListQuerySchema, MessageSchema, MessageUpdateInputSchema, NotificationListQuerySchema, NotificationSchema, ReactionInputSchema } from "@oryon/contracts/communication";
import { authenticate, AUTH_COOKIE_NAME } from "./auth.js";

export type CommunicationIO = { to(room: string): { emit(event: string, payload: unknown): void } };
const repository = new CommunicationRepository(getPrisma());
const permissionRepository = new PermissionRepository();

function header(request: FastifyRequest, name: string): string | undefined { const value = request.headers[name]; return typeof value === "string" && value.length > 0 ? value : undefined; }
function orgId(request: FastifyRequest): string { const value = header(request, "x-oryon-org"); if (!value) throw new Error("ORG_HEADER_MISSING"); return value; }
function token(request: FastifyRequest): { value: string; mode: "bearer" | "session" } { const auth = header(request, "authorization"); if (auth?.startsWith("Bearer ")) return { value: auth.slice(7).trim(), mode: "bearer" }; const raw = header(request, "cookie"); if (raw) for (const part of raw.split(";")) { const separator = part.indexOf("="); if (separator > 0 && part.slice(0, separator).trim() === AUTH_COOKIE_NAME) return { value: decodeURIComponent(part.slice(separator + 1).trim()), mode: "session" }; } throw new Error("UNAUTHENTICATED"); }
async function currentUser(request: FastifyRequest, organizationId: string) { const auth = token(request); const current = await authenticate(auth.value, auth.mode); if (current.orgId !== organizationId) throw new Error("UNAUTHENTICATED"); return current; }
function idempotency(request: FastifyRequest): void { if (!header(request, "idempotency-key")) throw new Error("IDEMPOTENCY_KEY_MISSING"); }
function envelope(request: FastifyRequest, data: unknown) { return { data, meta: { requestId: request.id, durationMs: 0 } }; }
function fail(request: FastifyRequest, reply: { code(status: number): { send(payload: unknown): unknown } }, error: unknown) { const message = error instanceof Error ? error.message : "Communication operation failed"; const status = message === "UNAUTHENTICATED" ? 401 : message === "PERMISSION_DENIED" ? 403 : ["NOT_FOUND", "CHANNEL_NOT_FOUND", "USER_NOT_FOUND", "FILE_NOT_FOUND", "OBJECT_TYPE_NOT_FOUND"].includes(message) ? 404 : ["CONFLICT", "PARENT_MESSAGE_NOT_FOUND"].includes(message) ? 409 : message === "ORG_HEADER_MISSING" ? 400 : message === "IDEMPOTENCY_KEY_MISSING" ? 400 : 400; const code = status === 401 ? "UNAUTHENTICATED" : status === 403 ? "PERMISSION_DENIED" : status === 404 ? "NOT_FOUND" : status === 409 ? "CONFLICT" : message === "ORG_HEADER_MISSING" ? "ORG_HEADER_MISSING" : "VALIDATION_FAILED"; return reply.code(status).send({ error: { code, httpStatus: status, message, requestId: request.id } }); }

async function channelAllowed(organizationId: string, userId: string, channel: { id: string; workspaceId: string | null; visibility: string; linkedObjectId: string | null }, action: "read" | "update" | "manage") {
  const snapshot = await permissionRepository.getSnapshot(organizationId, userId, "channel", channel.id);
  const resource = { orgId: organizationId, type: "channel", id: channel.id, workspaceId: channel.workspaceId, projectId: null, ownerId: null, teamId: null, classification: null };
  return can({ orgId: organizationId, ...snapshot }, resource, action).allowed;
}
function messageResponse(message: Awaited<ReturnType<CommunicationRepository["createMessage"]>>, userId: string) {
  const groups = new Map<string, { emoji: string; count: number; reacted: boolean }>();
  for (const reaction of message.reactions) { const current = groups.get(reaction.emoji); if (current) { current.count += 1; current.reacted ||= reaction.userId === userId; } else groups.set(reaction.emoji, { emoji: reaction.emoji, count: 1, reacted: reaction.userId === userId }); }
  return MessageSchema.parse({ ...message, scheduledFor: message.scheduledFor?.toISOString() ?? null, resolvedAt: message.resolvedAt?.toISOString() ?? null, pinnedAt: message.pinnedAt?.toISOString() ?? null, editedAt: message.editedAt?.toISOString() ?? null, createdAt: message.createdAt.toISOString(), author: { id: message.author.id, name: message.author.name, displayName: message.author.displayName, avatarUrl: message.author.avatarUrl, presence: message.author.presence }, reactions: [...groups.values()], permissions: { read: true, update: message.authorId === userId, delete: message.authorId === userId, react: true, reply: true, convert: true } });
}

export async function registerCommunicationRoutes(app: FastifyInstance, io: CommunicationIO): Promise<void> {
  app.get("/v1/channels", async (request, reply) => { try { const organizationId = orgId(request); const current = await currentUser(request, organizationId); const rows = await repository.listChannels(organizationId, current.userId); const unread = await repository.unreadCount(organizationId, current.userId); const result = rows.map((channel) => ChannelSchema.parse({ ...channel, archivedAt: channel.archivedAt?.toISOString() ?? null, createdAt: channel.createdAt.toISOString(), memberCount: 0, unreadCount: unread, permissions: { read: true, post: true, manage: channel.createdBy === current.userId } })); return reply.send(envelope(request, result)); } catch (error) { return fail(request, reply, error); } });
  app.post("/v1/channels", async (request, reply) => { try { idempotency(request); const organizationId = orgId(request); const current = await currentUser(request, organizationId); const input = ChannelCreateInputSchema.parse(request.body); const result = await repository.createChannel(organizationId, current.userId, input); io.to(`org:${organizationId}`).emit("channel.updated", CommunicationEventSchema.parse({ event: "channel.updated", channelId: result.id, messageId: null, notificationId: null, payload: { kind: "created", channelId: result.id } })); return reply.code(201).send(envelope(request, ChannelSchema.parse({ ...result, archivedAt: null, createdAt: result.createdAt.toISOString(), memberCount: 1, unreadCount: 0, permissions: { read: true, post: true, manage: true } }))); } catch (error) { return fail(request, reply, error); } });
  app.post("/v1/channels/direct", async (request, reply) => { try { idempotency(request); const organizationId = orgId(request); const current = await currentUser(request, organizationId); const input = DirectChannelCreateInputSchema.parse(request.body); const existing = await repository.findDirectChannel(organizationId, [current.userId, ...input.userIds]); const result = existing ?? await repository.createDirectChannel(organizationId, current.userId, input); io.to(`org:${organizationId}`).emit("channel.updated", CommunicationEventSchema.parse({ event: "channel.updated", channelId: result.id, messageId: null, notificationId: null, payload: { kind: existing ? "existing" : "created", channelId: result.id } })); return reply.send(envelope(request, ChannelSchema.parse({ ...result, archivedAt: result.archivedAt?.toISOString() ?? null, createdAt: result.createdAt.toISOString(), memberCount: result.kind === "DM" ? 2 : input.userIds.length + 1, unreadCount: 0, permissions: { read: true, post: true, manage: result.createdBy === current.userId } }))); } catch (error) { return fail(request, reply, error); } });
  app.get("/v1/channels/:channelId/messages", async (request, reply) => { try { const organizationId = orgId(request); const current = await currentUser(request, organizationId); const channel = await repository.getMembership(organizationId, (request.params as { channelId: string }).channelId, current.userId); if (!channel) throw new Error("NOT_FOUND"); if (!(await channelAllowed(organizationId, current.userId, channel.channel, "read"))) throw new Error("NOT_FOUND"); const query = MessageListQuerySchema.parse(request.query); const result = await repository.listMessages(organizationId, channel.channelId, current.userId, query.limit, query.cursor, query.parentId); const messages = result.messages.map((message) => messageResponse(message as Awaited<ReturnType<CommunicationRepository["createMessage"]>>, current.userId)); return reply.send(envelope(request, { items: messages, nextCursor: result.nextCursor })); } catch (error) { return fail(request, reply, error); } });
  app.get("/v1/channels/:channelId/catch-up", async (request, reply) => { try { const organizationId = orgId(request); const current = await currentUser(request, organizationId); const channel = await repository.getMembership(organizationId, (request.params as { channelId: string }).channelId, current.userId); if (!channel) throw new Error("NOT_FOUND"); if (!(await channelAllowed(organizationId, current.userId, channel.channel, "read"))) throw new Error("NOT_FOUND"); const query = CatchUpQuerySchema.parse(request.query); const rows = await repository.catchUp(organizationId, channel.channelId, current.userId, query.since ? new Date(query.since) : undefined, query.limit); return reply.send(envelope(request, rows.map((message) => messageResponse(message as Awaited<ReturnType<CommunicationRepository["createMessage"]>>, current.userId)))); } catch (error) { return fail(request, reply, error); } });
  app.post("/v1/channels/:channelId/messages", async (request, reply) => { try { idempotency(request); const organizationId = orgId(request); const current = await currentUser(request, organizationId); const channel = await repository.getMembership(organizationId, (request.params as { channelId: string }).channelId, current.userId); if (!channel || !(await channelAllowed(organizationId, current.userId, channel.channel, "read"))) throw new Error("PERMISSION_DENIED"); const input = MessageCreateInputSchema.parse(request.body); const message = await repository.createMessage(organizationId, current.userId, channel.channelId, input); const payload = messageResponse(message, current.userId); io.to(`channel:${channel.channelId}`).emit("message.created", payload); for (const mentionedUserId of [...new Set(input.mentions)].filter((id) => id !== current.userId)) io.to(`user:${mentionedUserId}`).emit("notification.created", { kind: "MENTION", messageId: message.id, channelId: channel.channelId }); return reply.code(201).send(envelope(request, payload)); } catch (error) { return fail(request, reply, error); } });
  app.patch("/v1/messages/:messageId", async (request, reply) => { try { idempotency(request); const organizationId = orgId(request); const current = await currentUser(request, organizationId); const input = MessageUpdateInputSchema.parse(request.body); const result = await repository.updateMessage(organizationId, current.userId, (request.params as { messageId: string }).messageId, input); const payload = messageResponse(result, current.userId); io.to(`channel:${result.channelId}`).emit("message.updated", payload); return reply.send(envelope(request, payload)); } catch (error) { return fail(request, reply, error); } });
  app.delete("/v1/messages/:messageId", async (request, reply) => { try { idempotency(request); const organizationId = orgId(request); const current = await currentUser(request, organizationId); const result = await repository.softDeleteMessage(organizationId, current.userId, (request.params as { messageId: string }).messageId); io.to(`channel:${result.channelId}`).emit("message.deleted", { messageId: result.id, channelId: result.channelId }); return reply.send(envelope(request, { deleted: true })); } catch (error) { return fail(request, reply, error); } });
  app.post("/v1/messages/:messageId/reactions", async (request, reply) => { try { idempotency(request); const organizationId = orgId(request); const current = await currentUser(request, organizationId); const input = ReactionInputSchema.parse(request.body); const result = await repository.addReaction(organizationId, current.userId, (request.params as { messageId: string }).messageId, input); io.to(`channel:${result.channelId}`).emit("reaction.updated", { messageId: (request.params as { messageId: string }).messageId, emoji: input.emoji, action: "add" }); return reply.send(envelope(request, { added: true })); } catch (error) { return fail(request, reply, error); } });
  app.delete("/v1/messages/:messageId/reactions/:emoji", async (request, reply) => { try { idempotency(request); const organizationId = orgId(request); const current = await currentUser(request, organizationId); const emoji = decodeURIComponent((request.params as { emoji: string }).emoji); const result = await repository.removeReaction(organizationId, current.userId, (request.params as { messageId: string }).messageId, emoji); io.to(`channel:${result.channelId}`).emit("reaction.updated", { messageId: (request.params as { messageId: string }).messageId, emoji, action: "remove" }); return reply.send(envelope(request, { removed: true })); } catch (error) { return fail(request, reply, error); } });
  app.get("/v1/notifications", async (request, reply) => { try { const organizationId = orgId(request); const current = await currentUser(request, organizationId); const query = NotificationListQuerySchema.parse(request.query); const rows = await repository.listNotifications(organizationId, current.userId, query.unreadOnly, query.limit); return reply.send(envelope(request, rows.map((row) => NotificationSchema.parse({ ...row, readAt: row.readAt?.toISOString() ?? null, archivedAt: row.archivedAt?.toISOString() ?? null, deliverAt: row.deliverAt.toISOString(), createdAt: row.createdAt.toISOString() })))); } catch (error) { return fail(request, reply, error); } });
  app.post("/v1/notifications/:notificationId/read", async (request, reply) => { try { idempotency(request); const organizationId = orgId(request); const current = await currentUser(request, organizationId); const row = await repository.markNotificationRead(organizationId, current.userId, (request.params as { notificationId: string }).notificationId); io.to(`user:${current.userId}`).emit("notification.created", { notificationId: row.id, readAt: row.readAt?.toISOString() ?? null }); return reply.send(envelope(request, NotificationSchema.parse({ ...row, readAt: row.readAt?.toISOString() ?? null, archivedAt: row.archivedAt?.toISOString() ?? null, deliverAt: row.deliverAt.toISOString(), createdAt: row.createdAt.toISOString() }))); } catch (error) { return fail(request, reply, error); } });
  app.post("/v1/notifications/read-all", async (request, reply) => { try { idempotency(request); const organizationId = orgId(request); const current = await currentUser(request, organizationId); const result = await repository.markAllNotificationsRead(organizationId, current.userId); return reply.send(envelope(request, { updated: result.count })); } catch (error) { return fail(request, reply, error); } });
  app.post("/v1/channels/:channelId/read", async (request, reply) => { try { idempotency(request); const organizationId = orgId(request); const current = await currentUser(request, organizationId); const membership = await repository.getMembership(organizationId, (request.params as { channelId: string }).channelId, current.userId); if (!membership) throw new Error("NOT_FOUND"); return reply.send(envelope(request, { readAt: new Date().toISOString() })); } catch (error) { return fail(request, reply, error); } });
  app.post("/v1/messages/:messageId/convert", async (request, reply) => { try { idempotency(request); const organizationId = orgId(request); const current = await currentUser(request, organizationId); const input = MessageConversionInputSchema.parse(request.body); const result = await repository.convertMessageToWorkObject(organizationId, current.userId, (request.params as { messageId: string }).messageId, input); io.to(`org:${organizationId}`).emit("message.updated", { messageId: result.messageId, convertedTo: result.workObjectId }); return reply.send(envelope(request, MessageConversionResponseSchema.parse(result))); } catch (error) { return fail(request, reply, error); } });
}
