import { randomUUID } from "node:crypto";
import type { FastifyInstance, FastifyRequest } from "fastify";
import { FileAssetSchema, FileCompleteInputSchema, FileSearchQuerySchema, FileUploadIntentInputSchema, FileUploadIntentSchema, PageCreateInputSchema, PagePublishInputSchema, PageSchema, PageUpdateInputSchema, PageVersionListSchema } from "@oryon/contracts/docs-files";
import { can } from "@oryon/core";
import { getPrisma } from "@oryon/db";
import { DocsFilesRepository, PermissionRepository } from "@oryon/db/repositories";
import { createDownloadUrl, createUploadUrl, headObject, storageKeyFor } from "@oryon/storage";
import { AUTH_COOKIE_NAME, authenticate } from "./auth.js";

const repository = new DocsFilesRepository(getPrisma());
const permissions = new PermissionRepository();

function header(request: FastifyRequest, name: string): string | undefined { const value = request.headers[name]; return typeof value === "string" && value.length > 0 ? value : undefined; }
function orgId(request: FastifyRequest): string { const value = header(request, "x-oryon-org"); if (!value) throw new Error("ORG_HEADER_MISSING"); return value; }
function authToken(request: FastifyRequest): { token: string; mode: "bearer" | "session" } { const value = header(request, "authorization"); if (value?.startsWith("Bearer ")) return { token: value.slice(7).trim(), mode: "bearer" }; const raw = header(request, "cookie"); if (raw) for (const part of raw.split(";")) { const index = part.indexOf("="); if (index > 0 && part.slice(0, index).trim() === AUTH_COOKIE_NAME) return { token: decodeURIComponent(part.slice(index + 1).trim()), mode: "session" }; } throw new Error("UNAUTHENTICATED"); }
async function currentUser(request: FastifyRequest, organizationId: string) { const auth = authToken(request); const current = await authenticate(auth.token, auth.mode); if (current.orgId !== organizationId) throw new Error("UNAUTHENTICATED"); return current; }
function requireKey(request: FastifyRequest): void { if (!header(request, "idempotency-key")) throw new Error("IDEMPOTENCY_KEY_MISSING"); }
function ok(request: FastifyRequest, data: unknown) { return { data, meta: { requestId: request.id, durationMs: 0 } }; }
function fail(request: FastifyRequest, reply: { code: (status: number) => { send: (value: unknown) => unknown } }, error: unknown) { const message = error instanceof Error ? error.message : "Docs operation failed"; const status = message === "UNAUTHENTICATED" ? 401 : message === "PERMISSION_DENIED" ? 403 : ["NOT_FOUND", "PARENT_PAGE_NOT_FOUND", "OWNER_NOT_FOUND", "FILE_NOT_FOUND", "STORAGE_OBJECT_SIZE_MISSING"].includes(message) ? 404 : ["PAGE_PARENT_CYCLE", "CONFLICT", "FILE_SIZE_MISMATCH", "FILE_MIME_MISMATCH", "UPLOAD_KEY_MISMATCH"].includes(message) ? 409 : message.startsWith("STORAGE_CONFIG_MISSING") ? 500 : 400; const code = status === 401 ? "UNAUTHENTICATED" : status === 403 ? "PERMISSION_DENIED" : status === 404 ? "NOT_FOUND" : status === 409 ? "CONFLICT" : status === 500 ? "INTERNAL" : message === "ORG_HEADER_MISSING" ? "ORG_HEADER_MISSING" : "VALIDATION_FAILED"; return reply.code(status).send({ error: { code, httpStatus: status, message, requestId: request.id } }); }
async function pagePermissions(organizationId: string, userId: string, page: { id: string; workspaceId: string | null; ownerId: string | null; classification: string | null }) { const snapshot = await permissions.getSnapshot(organizationId, userId, "page", page.id, page.classification); const resource = { orgId: organizationId, type: "page", id: page.id, workspaceId: page.workspaceId, projectId: null, ownerId: page.ownerId, teamId: null, classification: page.classification }; const actions = ["read", "create", "update", "delete", "share", "export", "manage"] as const; return Object.fromEntries(actions.map((action) => [action, can({ orgId: organizationId, ...snapshot }, resource, action).allowed])) as { read: boolean; create: boolean; update: boolean; delete: boolean; share: boolean; export: boolean; manage: boolean }; }
async function pageOut(organizationId: string, userId: string, page: Awaited<ReturnType<DocsFilesRepository["findPage"]>>) { if (!page) throw new Error("NOT_FOUND"); const permissionsForPage = await pagePermissions(organizationId, userId, page); if (!permissionsForPage.read) throw new Error("NOT_FOUND"); return PageSchema.parse({ ...page, position: page.position.toString(), contentYjsBase64: page.contentYjs ? Buffer.from(page.contentYjs).toString("base64") : null, verifiedAt: page.verifiedAt?.toISOString() ?? null, nextReviewAt: page.nextReviewAt?.toISOString() ?? null, publishedAt: page.publishedAt?.toISOString() ?? null, updatedAt: page.updatedAt.toISOString(), createdAt: page.createdAt.toISOString(), permissions: permissionsForPage }); }
async function fileOut(organizationId: string, userId: string, file: Awaited<ReturnType<DocsFilesRepository["findFile"]>>, signed: boolean) { if (!file) throw new Error("NOT_FOUND"); const snapshot = await permissions.getSnapshot(organizationId, userId, "file_asset", file.id, file.classification); const resource = { orgId: organizationId, type: "file_asset", id: file.id, workspaceId: null, projectId: null, ownerId: file.uploadedBy, teamId: null, classification: file.classification }; const read = can({ orgId: organizationId, ...snapshot }, resource, "read").allowed; const update = can({ orgId: organizationId, ...snapshot }, resource, "update").allowed; const exportAllowed = can({ orgId: organizationId, ...snapshot }, resource, "export").allowed; const deleteAllowed = can({ orgId: organizationId, ...snapshot }, resource, "delete").allowed; if (!read) throw new Error("NOT_FOUND"); return FileAssetSchema.parse({ id: file.id, name: file.name, mimeType: file.mimeType, sizeBytes: file.sizeBytes.toString(), storageKey: file.storageKey, version: file.version, classification: file.classification, checksumSha256: file.checksumSha256, createdAt: file.createdAt.toISOString(), downloadUrl: signed && exportAllowed ? await createDownloadUrl(file.storageKey) : null, permissions: { read, update, export: exportAllowed, delete: deleteAllowed } }); }

export async function registerDocsFilesRoutesV2(app: FastifyInstance): Promise<void> {
  app.get("/v1/pages", async (request, reply) => { try { const organizationId = orgId(request); const user = await currentUser(request, organizationId); const query = request.query as { workspaceId?: string; limit?: string }; const rows = await repository.listPages(organizationId, query.workspaceId, Number(query.limit ?? "100")); const result = []; for (const row of rows) try { result.push(await pageOut(organizationId, user.userId, row)); } catch (error) { if (!(error instanceof Error && error.message === "NOT_FOUND")) throw error; } return reply.send(ok(request, result)); } catch (error) { return fail(request, reply, error); } });
  app.post("/v1/pages", async (request, reply) => { try { requireKey(request); const organizationId = orgId(request); const user = await currentUser(request, organizationId); const input = PageCreateInputSchema.parse(request.body); const snapshot = await permissions.getSnapshot(organizationId, user.userId, "page", "__collection__"); const resource = { orgId: organizationId, type: "page", id: "__collection__", workspaceId: input.workspaceId ?? null, projectId: null, ownerId: null, teamId: null, classification: input.classification ?? null }; if (!can({ orgId: organizationId, ...snapshot }, resource, "create").allowed) throw new Error("PERMISSION_DENIED"); return reply.code(201).send(ok(request, await pageOut(organizationId, user.userId, await repository.createPage(organizationId, user.userId, input)))); } catch (error) { return fail(request, reply, error); } });
  app.get("/v1/pages/:id", async (request, reply) => { try { const organizationId = orgId(request); const user = await currentUser(request, organizationId); return reply.send(ok(request, await pageOut(organizationId, user.userId, await repository.findPage(organizationId, (request.params as { id: string }).id)))); } catch (error) { return fail(request, reply, error); } });
  app.patch("/v1/pages/:id", async (request, reply) => { try { requireKey(request); const organizationId = orgId(request); const user = await currentUser(request, organizationId); const { id } = request.params as { id: string }; const input = PageUpdateInputSchema.parse(request.body); const page = await repository.findPage(organizationId, id); if (!page) throw new Error("NOT_FOUND"); const snapshot = await permissions.getSnapshot(organizationId, user.userId, "page", id, page.classification); const resource = { orgId: organizationId, type: "page", id, workspaceId: page.workspaceId, projectId: null, ownerId: page.ownerId, teamId: null, classification: page.classification }; if (!can({ orgId: organizationId, ...snapshot }, resource, "update").allowed) throw new Error("PERMISSION_DENIED"); if (["classification", "indexable", "publishedSlug"].some((field) => field in input) && !can({ orgId: organizationId, ...snapshot }, resource, "manage").allowed) throw new Error("PERMISSION_DENIED"); return reply.send(ok(request, await pageOut(organizationId, user.userId, await repository.updatePage(organizationId, user.userId, id, input)))); } catch (error) { return fail(request, reply, error); } });
  app.get("/v1/pages/:id/versions", async (request, reply) => { try { const organizationId = orgId(request); const user = await currentUser(request, organizationId); const page = await repository.findPage(organizationId, (request.params as { id: string }).id); if (!page || !(await pagePermissions(organizationId, user.userId, page)).read) throw new Error("NOT_FOUND"); const versions = await repository.listVersions(organizationId, page.id); return reply.send(ok(request, PageVersionListSchema.parse(versions.map((version) => ({ id: version.id, pageId: version.pageId, version: version.version, summary: version.summary, authorId: version.authorId, snapshotBytes: Buffer.from(version.snapshot).toString("base64"), createdAt: version.createdAt.toISOString() }))))); } catch (error) { return fail(request, reply, error); } });
  app.post("/v1/pages/:id/publish", async (request, reply) => { try { requireKey(request); const organizationId = orgId(request); const user = await currentUser(request, organizationId); const { id } = request.params as { id: string }; const input = PagePublishInputSchema.parse(request.body); const page = await repository.findPage(organizationId, id); if (!page) throw new Error("NOT_FOUND"); const snapshot = await permissions.getSnapshot(organizationId, user.userId, "page", id, page.classification); const resource = { orgId: organizationId, type: "page", id, workspaceId: page.workspaceId, projectId: null, ownerId: page.ownerId, teamId: null, classification: page.classification }; if (!can({ orgId: organizationId, ...snapshot }, resource, "manage").allowed) throw new Error("PERMISSION_DENIED"); return reply.send(ok(request, await pageOut(organizationId, user.userId, await repository.publishPage(organizationId, user.userId, id, input.publish ? input.publishedSlug : null)))); } catch (error) { return fail(request, reply, error); } });
  app.post("/v1/files/upload-intent", async (request, reply) => { try { requireKey(request); const organizationId = orgId(request); const user = await currentUser(request, organizationId); const input = FileUploadIntentInputSchema.parse(request.body); const snapshot = await permissions.getSnapshot(organizationId, user.userId, "file_asset", "__collection__"); const resource = { orgId: organizationId, type: "file_asset", id: "__collection__", workspaceId: null, projectId: null, ownerId: user.userId, teamId: null, classification: null }; if (!can({ orgId: organizationId, ...snapshot }, resource, "create").allowed) throw new Error("PERMISSION_DENIED"); const uploadId = randomUUID(); const fileId = randomUUID(); const storageKey = storageKeyFor(organizationId, user.userId, fileId, input.name); const upload = await createUploadUrl({ storageKey, mimeType: input.mimeType }); return reply.send(ok(request, FileUploadIntentSchema.parse({ uploadId, fileId, storageKey, uploadUrl: upload.uploadUrl, expiresIn: upload.expiresIn }))); } catch (error) { return fail(request, reply, error); } });
  app.post("/v1/files/complete", async (request, reply) => { try { requireKey(request); const organizationId = orgId(request); const user = await currentUser(request, organizationId); const input = FileCompleteInputSchema.parse(request.body); const expectedKey = storageKeyFor(organizationId, user.userId, input.fileId, input.name); if (expectedKey !== input.storageKey) throw new Error("UPLOAD_KEY_MISMATCH"); const head = await headObject(expectedKey); if (head.sizeBytes !== input.sizeBytes) throw new Error("FILE_SIZE_MISMATCH"); if (head.mimeType && head.mimeType !== input.mimeType) throw new Error("FILE_MIME_MISMATCH"); return reply.code(201).send(ok(request, await fileOut(organizationId, user.userId, await repository.createFile(organizationId, user.userId, { ...input, storageKey: expectedKey }), false))); } catch (error) { return fail(request, reply, error); } });
  app.get("/v1/files/:id", async (request, reply) => { try { const organizationId = orgId(request); const user = await currentUser(request, organizationId); return reply.send(ok(request, await fileOut(organizationId, user.userId, await repository.findFile(organizationId, (request.params as { id: string }).id), true))); } catch (error) { return fail(request, reply, error); } });
  app.get("/v1/search/text", async (request, reply) => { try { const organizationId = orgId(request); const user = await currentUser(request, organizationId); const query = FileSearchQuerySchema.parse(request.query); const result = await repository.search(organizationId, query.q, query.limit); const pages = []; for (const page of result.pages) try { pages.push(await pageOut(organizationId, user.userId, page)); } catch (error) { if (!(error instanceof Error && error.message === "NOT_FOUND")) throw error; } const files = []; for (const file of result.files) try { files.push(await fileOut(organizationId, user.userId, file, false)); } catch (error) { if (!(error instanceof Error && error.message === "NOT_FOUND")) throw error; } return reply.send(ok(request, { pages, files })); } catch (error) { return fail(request, reply, error); } });
}
