import { createHmac, randomUUID } from "node:crypto";
import type { FastifyInstance, FastifyRequest } from "fastify";
import { can } from "@oryon/core";
import { getPrisma } from "@oryon/db";
import { PermissionRepository, PlatformRepository, WorkObjectRepository } from "@oryon/db/repositories";
import { ApiKeyCreatedSchema, ApiKeyCreateInputSchema, ApiKeyRevokeInputSchema, ApiKeySummarySchema, AuditEntrySchema, AuditQuerySchema, ExportWorkObjectsInputSchema, ImportWorkObjectsInputSchema, ImportWorkObjectsResponseSchema, PlatformHealthSchema, WebhookCreateInputSchema, WebhookSummarySchema, WebhookTestResponseSchema, WebhookUpdateInputSchema } from "@oryon/contracts/platform-release";
import { AUTH_COOKIE_NAME, authenticate } from "./auth.js";

const db = getPrisma();
const platform = new PlatformRepository(db);
const permissions = new PermissionRepository();
const objects = new WorkObjectRepository(db);
function header(request: FastifyRequest, name: string): string | undefined { const value = request.headers[name]; return typeof value === "string" && value.length > 0 ? value : undefined; }
function orgIdOf(request: FastifyRequest): string { const value = header(request, "x-oryon-org"); if (!value) throw new Error("ORG_HEADER_MISSING"); return value; }
function requireIdempotency(request: FastifyRequest): void { if (!header(request, "idempotency-key")) throw new Error("IDEMPOTENCY_KEY_MISSING"); }
function tokenOf(request: FastifyRequest): { token: string; mode: "bearer" | "session" } | undefined { const bearer = header(request, "authorization"); if (bearer?.startsWith("Bearer ")) return { token: bearer.slice(7).trim(), mode: "bearer" }; const cookie = header(request, "cookie"); if (!cookie) return undefined; const item = cookie.split(";").map(value => value.trim()).find(value => value.startsWith(`${AUTH_COOKIE_NAME}=`)); return item ? { token: decodeURIComponent(item.slice(AUTH_COOKIE_NAME.length + 1)), mode: "session" } : undefined; }
async function principal(request: FastifyRequest, orgId: string): Promise<{ userId: string; apiKey: boolean }> { const key = header(request, "x-oryon-api-key"); if (key) { const userId = await platform.authenticateApiKey(orgId, key); if (!userId) throw new Error("UNAUTHENTICATED"); return { userId, apiKey: true }; } const auth = tokenOf(request); if (!auth) throw new Error("UNAUTHENTICATED"); const session = await authenticate(auth.token, auth.mode); if (session.orgId !== orgId) throw new Error("UNAUTHENTICATED"); return { userId: session.userId, apiKey: false }; }
function resource(orgId: string) { return { orgId, type: "organization", id: orgId, workspaceId: null, projectId: null, ownerId: null, teamId: null, classification: null }; }
async function assertManage(request: FastifyRequest, orgId: string) { const actor = await principal(request, orgId); const snapshot = await permissions.getSnapshot(orgId, actor.userId, "organization", orgId); const decision = can({ orgId, ...snapshot }, resource(orgId), "manage"); if (!decision.allowed) throw new Error("PERMISSION_DENIED"); return actor; }
function envelope(request: FastifyRequest, data: unknown) { return { data, meta: { requestId: request.id, durationMs: 0 } }; }
function fail(request: FastifyRequest, error: unknown) { const message = error instanceof Error ? error.message : "Platform operation failed"; const map: Record<string, [string, number]> = { ORG_HEADER_MISSING: ["ORG_HEADER_MISSING", 400], UNAUTHENTICATED: ["UNAUTHENTICATED", 401], PERMISSION_DENIED: ["PERMISSION_DENIED", 403], NOT_FOUND: ["NOT_FOUND", 404], ORG_NOT_FOUND: ["NOT_FOUND", 404], IDEMPOTENCY_KEY_MISSING: ["VALIDATION_FAILED", 400] }; const [code, status] = map[message] ?? ["VALIDATION_FAILED", 400]; return { code, status, body: { error: { code, httpStatus: status, message, requestId: request.id } } }; }

export async function registerPlatformRoutes(app: FastifyInstance): Promise<void> {
  app.get("/v1/platform/health", async (request, reply) => { try { await db.$queryRawUnsafe("SELECT 1"); return reply.send(envelope(request, PlatformHealthSchema.parse({ status: "ok", service: "oryon-api", version: "0.1.0", checks: { database: "ok", openapi: "ok", security: "ok" }, timestamp: new Date().toISOString() }))); } catch (error) { request.log.error({ error }, "platform health degraded"); return reply.code(503).send(envelope(request, PlatformHealthSchema.parse({ status: "degraded", service: "oryon-api", version: "0.1.0", checks: { database: "error", openapi: "ok", security: "ok" }, timestamp: new Date().toISOString() }))); } });
  app.get("/v1/platform/api-keys", async (request, reply) => { try { const orgId = orgIdOf(request); await assertManage(request, orgId); return reply.send(envelope(request, (await platform.listApiKeys(orgId)).map(item => ApiKeySummarySchema.parse(item)))); } catch (error) { const result = fail(request, error); return reply.code(result.status).send(result.body); } });
  app.post("/v1/platform/api-keys", async (request, reply) => { try { requireIdempotency(request); const orgId = orgIdOf(request); const actor = await assertManage(request, orgId); const body = ApiKeyCreateInputSchema.parse(request.body); return reply.code(201).send(envelope(request, ApiKeyCreatedSchema.parse(await platform.createApiKey(orgId, actor.userId, body.label, body.expiresAt)))); } catch (error) { const result = fail(request, error); return reply.code(result.status).send(result.body); } });
  app.delete("/v1/platform/api-keys/:id", async (request, reply) => { try { requireIdempotency(request); const orgId = orgIdOf(request); const actor = await assertManage(request, orgId); const params = request.params as { id: string }; const body = ApiKeyRevokeInputSchema.parse(request.body ?? {}); await platform.revokeApiKey(orgId, actor.userId, params.id, body.reason); return reply.send(envelope(request, { revoked: true })); } catch (error) { const result = fail(request, error); return reply.code(result.status).send(result.body); } });
  app.get("/v1/platform/webhooks", async (request, reply) => { try { const orgId = orgIdOf(request); await assertManage(request, orgId); return reply.send(envelope(request, (await platform.listWebhooks(orgId)).map(item => WebhookSummarySchema.parse(item)))); } catch (error) { const result = fail(request, error); return reply.code(result.status).send(result.body); } });
  app.post("/v1/platform/webhooks", async (request, reply) => { try { requireIdempotency(request); const orgId = orgIdOf(request); const actor = await assertManage(request, orgId); const body = WebhookCreateInputSchema.parse(request.body); return reply.code(201).send(envelope(request, WebhookSummarySchema.parse(await platform.createWebhook(orgId, actor.userId, body)))); } catch (error) { const result = fail(request, error); return reply.code(result.status).send(result.body); } });
  app.patch("/v1/platform/webhooks/:id", async (request, reply) => { try { requireIdempotency(request); const orgId = orgIdOf(request); const actor = await assertManage(request, orgId); const params = request.params as { id: string }; const body = WebhookUpdateInputSchema.parse(request.body); return reply.send(envelope(request, WebhookSummarySchema.parse(await platform.updateWebhook(orgId, actor.userId, params.id, body)))); } catch (error) { const result = fail(request, error); return reply.code(result.status).send(result.body); } });
  app.post("/v1/platform/webhooks/:id/test", async (request, reply) => { try { requireIdempotency(request); const orgId = orgIdOf(request); await assertManage(request, orgId); const params = request.params as { id: string }; const hook = (await platform.getWebhookSecrets(orgId)).find(item => item.id === params.id && item.active); if (!hook) throw new Error("NOT_FOUND"); const payload = JSON.stringify({ id: `evt_${randomUUID()}`, name: "platform.webhook.test", version: 1, orgId, occurredAt: new Date().toISOString(), actor: null, subject: { type: "WebhookEndpoint", id: hook.id }, payload: { test: true } }); const signature = createHmac("sha256", hook.secret).update(payload).digest("hex"); const started = Date.now(); const response = await fetch(hook.url, { method: "POST", headers: { "content-type": "application/json", "x-oryon-signature": `sha256=${signature}`, "x-oryon-event": "platform.webhook.test" }, body: payload, signal: AbortSignal.timeout(10000) }); return reply.send(envelope(request, WebhookTestResponseSchema.parse({ delivered: response.ok, statusCode: response.status, durationMs: Date.now() - started }))); } catch (error) { const result = fail(request, error); return reply.code(result.status).send(result.body); } });
  app.get("/v1/platform/audit", async (request, reply) => { try { const orgId = orgIdOf(request); await assertManage(request, orgId); const query = AuditQuerySchema.parse(request.query); return reply.send(envelope(request, (await platform.listAudit(orgId, query)).map(row => AuditEntrySchema.parse(row)))); } catch (error) { const result = fail(request, error); return reply.code(result.status).send(result.body); } });
  app.get("/v1/platform/export/work-objects", async (request, reply) => { try { const orgId = orgIdOf(request); const actor = await assertManage(request, orgId); const query = ExportWorkObjectsInputSchema.parse(request.query); const rows = await objects.list({ orgId, typeKey: query.typeKey, workspaceId: query.workspaceId, limit: query.limit }); return reply.header("Content-Type", "application/json; charset=utf-8").header("Content-Disposition", `attachment; filename=oryon-work-objects-${new Date().toISOString().slice(0, 10)}.json`).send({ data: { exportedBy: actor.userId, count: rows.length, objects: rows.map(row => ({ ...row, customFields: query.includeCustomFields ? row.customFields : undefined })) }, meta: { requestId: request.id, durationMs: 0 } }); } catch (error) { const result = fail(request, error); return reply.code(result.status).send(result.body); } });
  app.post("/v1/platform/import/work-objects", async (request, reply) => { try { requireIdempotency(request); const orgId = orgIdOf(request); const actor = await assertManage(request, orgId); const body = ImportWorkObjectsInputSchema.parse(request.body); const ids: string[] = []; for (const item of body.objects) ids.push(await objects.create(orgId, actor.userId, { typeKey: item.typeKey, title: item.title, description: item.description, status: item.status, priority: item.priority, tags: item.tags ?? [], customFields: item.customFields ?? {}, externalRef: item.externalRef ?? null })); return reply.send(envelope(request, ImportWorkObjectsResponseSchema.parse({ imported: ids.length, ids }))); } catch (error) { const result = fail(request, error); return reply.code(result.status).send(result.body); } });
}
