export const workCopy = {
	eyebrow: "WORK OBJECT ENGINE",
	title: "Trabalho universal",
	subtitle: "Crie e opere qualquer tipo de trabalho no mesmo motor, com estados, responsáveis, contexto e campos personalizados.",	objects: "Objectos",
	types: "Tipos",
	newObject: "Novo objecto",
	newType: "Novo tipo",
	refresh: "Actualizar",
	type: "Tipo",
	titleField: "Título",
	description: "Descrição",
	priority: "Prioridade",
	owner: "Responsável",
	status: "Estado",
	dueAt: "Data limite",
	customFields: "Campos personalizados",
	create: "Criar objecto",
	creating: "A criar...",
	update: "Guardar alterações",
	updating: "A guardar...",
	delete: "Eliminar",
	deleting: "A eliminar...",
	noObjects: "Ainda não existem objectos neste workspace.",
	noTypes: "Ainda não existem tipos disponíveis.",
	selectedObject: "Objecto seleccionado",
	engineStatus: "Motor operacional",
	engineDescription: "O mesmo modelo suporta trabalho nativo e tipos criados pela empresa.",	key: "Chave",
	name: "Nome",
	pluralName: "Nome plural",
	idPrefix: "Prefixo",
	statuses: "Estados",
	transitions: "Transições",
	fields: "Campos",
	fieldKey: "Chave do campo",
	fieldLabel: "Etiqueta",
	fieldType: "Tipo de campo",
	addField: "Adicionar campo",
	required: "Obrigatório",
	requiredMark: " *",
	createType: "Criar tipo",
	creatingType: "A criar tipo...",
	initial: "Estado inicial",
	success: "Operação concluída.",
	error: "Não foi possível concluir a operação.",
	back: "Voltar",
	permissionDenied: "Não tem permissão para esta operação.",
	chooseType: "Escolha um tipo",
	chooseStatus: "Escolha um estado",
	optional: "Opcional",
	emptyValue: "Não definido",
	workspace: "Workspace",
	parent: "Objecto pai",
	classification: "Classificação",
	progress: "Progresso",
	unsaved: "Alterações por guardar",
	loading: "A carregar...",
};

export const priorityOptions = ["LOWEST", "LOW", "NORMAL", "HIGH", "URGENT"] as const;
export const fieldTypeOptions = ["TEXT", "NUMBER", "BOOLEAN", "DATE", "SELECT", "MULTI_SELECT", "USER", "OBJECT"] as const;
