export const authCopy = {
	eyebrow: "ORYON OS",
	title: "Entre no sistema operativo da sua empresa.",
	subtitle: "Use o seu email empresarial. Vamos enviar um acesso seguro e de uso único.",
	organization: "ID da organização",
	email: "Email empresarial",
	continue: "Enviar acesso",
	sentTitle: "Verifique o seu email.",
	sentBody: "O acesso enviado é válido por alguns minutos e só pode ser usado uma vez.",
	devToken: "Token de desenvolvimento",
	openAccess: "Abrir acesso",
	loading: "A validar acesso...",
	success: "Sessão iniciada.",
	goToWorkspace: "Entrar no workspace",
	logout: "Sair",
	identity: "Identidade empresarial",
	workspaces: "Workspaces",
	teams: "Equipas",
	member: "Membro",
	role: "Função",
	notAvailable: "Sessão não disponível.",
	backToLogin: "Voltar ao acesso",
};
